# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table persons (
  id                            integer generated by default as identity not null,
  emals                         varchar(255),
  passwords                     varchar(255),
  authorisations                boolean default false not null,
  constraint pk_persons primary key (id)
);


# --- !Downs

drop table if exists persons;

